#!/usr/bin/python3

import zymkey
import binascii
import hashlib
import rlp
from Crypto.Hash import keccak
from rlp import encode
from rlp.sedes import Binary, big_endian_int, binary
from eth_account._utils.transactions import serializable_unsigned_transaction_from_dict, encode_transaction
from web3 import Web3

class Transaction(rlp.Serializable):
    fields = [
        ("nonce", big_endian_int),
        ("gas_price", big_endian_int),
        ("gas", big_endian_int),
        ("to", Binary.fixed_length(20, allow_empty=True)),
        ("value", big_endian_int),
        ("data", binary),
        ("v", big_endian_int),
        ("r", big_endian_int),
        ("s", big_endian_int),
    ]

#Utility function for checking the from/to/(v,r,s) values of a raw transaction
def decode_raw_tx(raw_tx):
    tx = rlp.decode(raw_tx, Transaction)
    from_addr = w3.eth.account.recover_transaction(raw_tx)
    to_addr = w3.toChecksumAddress(tx.to) if tx.to else None
    r = hex(tx.r)
    s = hex(tx.s)
    chain_id = (tx.v - 35) // 2 if tx.v % 2 else (tx.v - 36) // 2
    print("\nDecoded raw transaction check:\nfrom:\n%s\nto:\n%s\nr:\n%s\ns:\n%s\nv:\n%s" % (from_addr, to_addr, r, s, tx.v))
    return tx

#create web3 instance, from infura project (node) connecting to ropsten test network
w3 = Web3(Web3.HTTPProvider('https://ropsten.infura.io/v3/bac2734b0e144a6dbb46c0e118ce1ef7'))

#Example receiver's address
addr = '0x15C25E6EB5dE729d7e310d059e59659cCB86E6f6'

#MAKE SURE TO GENERATE A "secp256k1" KEY PAIR ON THE HSM6, this example uses slot 20
#Get ECDSA secp256k1 public key from zymkey and generate our Ethereum sender's checksum address
zymkey_pub_key_slot = 16
pub_key = zymkey.client.get_public_key(zymkey_pub_key_slot)

keccak_hash = keccak.new(digest_bits=256)
keccak_hash.update(pub_key)
keccak_digest = keccak_hash.hexdigest()
# Take the last 20 bytes
wallet_len = 40
wallet_addr = "0x" + keccak_digest[-wallet_len:]

checksum = Web3.toChecksumAddress(wallet_addr)

#estimate gas
gas = w3.eth.estimate_gas({'to': addr, 'value': 1})

#grab nonce value of sender's account. nonce = number of transactions
nonce = w3.eth.getTransactionCount(checksum)

#Ropsten chain ID is 3
chain_id = 3

# prepare the transaction, chainID 3 is ropsten
transaction = {
    'to': addr,
    'gas': gas,
    'gasPrice': 5000000,
    'nonce': nonce,
    'value': 1,
    'data': '0x',
    'chainId': chain_id
}

loop_counter = 100
pass_counter = 0
pass_counter_s_changed = 0
fail_counter = 0
fail_counter_s_changed = 0
#----------------------------------------Send Transaction with zymkey signature-----------------------------------------------------------------
while loop_counter != 0:
    print("Countdown iteration: %i\n" % (loop_counter))
    #Sign a transaction with a signature generated by hsm6

    #Serialize the transaction
    serializable_transaction = serializable_unsigned_transaction_from_dict(transaction)

    #RLP encode the transaction
    encoded_transaction = encode(serializable_transaction)

    #Per Ethereum standards, Keccak hash rlp encoded transaction
    keccak_hash=keccak.new(digest_bits=256)
    keccak_hash.update(encoded_transaction)

    N = 115792089237316195423570985008687907852837564279074904382605163141518161494337
    # sign the transaction hash and calculate v, r, s values
    signature, parity = zymkey.client.sign_digest(keccak_hash, zymkey_pub_key_slot)

    #Signature consists of a R, S, V
    #R is the first half of the signature converted to int
    #S is the second half of the signature converted to int
    #From EIP 155, V = chainId * 2 + 35 + parity value of y value of public key
    r = int.from_bytes(signature[:32], "big")
    s = int.from_bytes(signature[-32:], "big")
    s_changed = False
    y = int(parity.value)
    if((s*2) >= N):
       y ^= 1
       s = N - s
       s_changed = True

    v = chain_id * 2 + 35 + y

    # RLP encode the transaction along with the full signature
    encoded_transaction = encode_transaction(serializable_transaction, vrs=(v, r, s))

    from_addr = w3.eth.account.recover_transaction(encoded_transaction)

    if(from_addr == checksum):
        pass_counter += 1
        print("Pass!\n")
        if(s_changed):
            pass_counter_s_changed += 1
    else:
        fail_counter += 1
        print("Fail!\n")
        if(s_changed):
            fail_counter_s_changed += 1
    loop_counter -= 1

print("Runs: %i\n" % (pass_counter + fail_counter))
print("From Address matched Checksum\n Pass: %i Fails: %i\n" % (pass_counter, fail_counter))
